# -*- coding: utf-8 -*-
"""workshop-day-2-python-and-ML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a340OS8cNvNr-Ps_hwvv9JTreGQLuDh8
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ==========================================================
# STEP 2 - LOAD DATASET
# ==========================================================

df = pd.read_csv("gaming_addiction (3).csv")
#

# ------------------------------------------------------------------
# Load Dataset
# ------------------------------------------------------------------
df = pd.read_csv("gaming_addiction (3).csv")

print(df.head())
print(df.info())
print(df.describe(include="all"))
print("\nMissing Values")
print(df.isnull().sum())

# ------------------------------------------------------------------
# Data Cleaning
# ------------------------------------------------------------------
df["subscription_status"] = df["subscription_status"].fillna(df["subscription_status"].mode()[0])
df["depression_indicator"] = df["depression_indicator"].fillna(df["depression_indicator"].mode()[0])
df["gpa_or_performance_score"] = df["gpa_or_performance_score"].fillna(df["gpa_or_performance_score"].median())
df.drop(columns=["addiction_severity"], inplace=True, errors="ignore")

print("\nMissing Values")
print(df.isnull().sum())

# ==========================================================
# STEP 2 : REMOVE IDENTIFIER COLUMN
# ==========================================================

if "user_id" in df.columns:
    df = df.drop(columns=["user_id"])

# ==========================================================
# STEP 3 : CONVERT CATEGORICAL DATA
# ==========================================================

print("\nConverting categorical columns...")

categorical_cols = df.select_dtypes(include=["object"]).columns

df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

print("Dataset Shape After Encoding:", df.shape)

# ==========================================================
# STEP 4 : SELECT FEATURES
# ==========================================================

print("\nPreparing features...")

X = df.copy()

# ==========================================================
# STEP 5 : FEATURE SCALING
# ==========================================================

print("Scaling data...")

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# ==========================================================
# STEP 6 : ELBOW METHOD
# ==========================================================

print("\nFinding optimal K...")

wcss = []

for k in range(1,11):
    model = KMeans(n_clusters=k,
                   random_state=42,
                   n_init=10)

    model.fit(X_scaled)
    wcss.append(model.inertia_)

plt.figure(figsize=(8,5))
plt.plot(range(1,11),wcss,marker="o")
plt.title("Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.grid(True)
plt.show()

print(""" Choose the point where the graph bends. That value is usually the optimal number of clusters. For this example we use K = 3. """)

# ==========================================================
# STEP 7 : TRAIN KMEANS
# ==========================================================

k = 3

kmeans = KMeans(
    n_clusters=k,
    random_state=42,
    n_init=10
)

clusters = kmeans.fit_predict(X_scaled)

df["Cluster"] = clusters

print("\nCluster Counts")
print(df["Cluster"].value_counts())

# ==========================================================
# STEP 8 : EVALUATION
# ==========================================================

score = silhouette_score(X_scaled, clusters)

print("\nSilhouette Score =", round(score,3))

if score > 0.7:
    print("Excellent clustering")
elif score > 0.5:
    print("Good clustering")
elif score > 0.3:
    print("Average clustering")
else:
    print("Poor clustering")

# ==========================================================
# STEP 9 : PCA VISUALIZATION
# ==========================================================

print("\nReducing dimensions using PCA...")

pca = PCA(n_components=2)

reduced = pca.fit_transform(X_scaled)

plt.figure(figsize=(8,6))

plt.scatter(
    reduced[:,0],
    reduced[:,1],
    c=clusters
)

plt.title("K-Means Clustering")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.show()