# -*- coding: utf-8 -*-
"""Workshop-1-python-and-ML-page-2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-iNJZZkK2vUkWyNSJqoEDap1iDXYbMq-
"""

from google.colab import files
uploaded = files.upload()

# ===============================================================
# STEP 1 : IMPORT THE REQUIRED LIBRARIES
# ===============================================================

# Pandas is used for reading and working with datasets
import pandas as pd

# NumPy is used for mathematical calculations
import numpy as np

# Matplotlib is used for creating graphs
import matplotlib.pyplot as plt

# Splits dataset into Training and Testing data
from sklearn.model_selection import train_test_split

# Linear Regression Algorithm
from sklearn.linear_model import LinearRegression

# Evaluation Metrics
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

print("="*60)
print("Libraries Imported Successfully")
print("="*60)

# ===============================================================
# STEP 2 : LOAD THE DATASET
# ===============================================================

# Read the Excel file
# Make sure the file is in the same folder
# If using Google Colab, upload the file first.

df = pd.read_csv("WineQT.csv")

print("\nDataset Loaded Successfully")

# ===============================================================
# STEP 3 : DISPLAY FIRST FIVE RECORDS
# ===============================================================

print("\nFirst Five Rows")
print(df.head())

# ===============================================================
# STEP 4 : UNDERSTAND THE DATASET
# ===============================================================

print("\nDataset Information")
print(df.info())

print("\nShape of Dataset")
print(df.shape)

print("\nColumn Names")
print(df.columns)

# ===============================================================
# STEP 5 : CHECK FOR MISSING VALUES
# ===============================================================

print("\nMissing Values")
print(df.isnull().sum())

# If missing values exist, remove them.
df = df.dropna()

# ===============================================================
# STEP 6 : DESCRIPTIVE STATISTICS
# ===============================================================

print("\nStatistical Summary")
print(df.describe())

# ===============================================================
# STEP 7 : SELECT FEATURES
# ===============================================================

# Features are INPUT variables.
# We believe these variables influence the wine quality.

X = df.drop(columns=['quality', 'Id'])

print("\nFeatures")
print(X.head())

# ===============================================================
# STEP 8 : SELECT TARGET VARIABLE
# ===============================================================

# Target variable is what we want to predict.

y = df["quality"]

print("\nTarget Variable")
print(y.head())

# ===============================================================
# STEP 9 : TRAIN TEST SPLIT
# ===============================================================

# Why split the data?
#
# We train the model on one part of the data
# and test it on unseen data.
#
# This tells us how well the model performs.

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("\nTraining Data Shape")
print(X_train.shape)

print("\nTesting Data Shape")
print(X_test.shape)

# ===============================================================
# STEP 10 : CREATE THE MODEL
# ===============================================================

# Create an empty Linear Regression model

model = LinearRegression()

print("\nLinear Regression Model Created")

# ===============================================================
# STEP 11 : TRAIN THE MODEL
# ===============================================================

# The model learns the relationship between
# Features and Target.

model.fit(X_train, y_train)

print("\nModel Training Completed")

# ===============================================================
# STEP 12 : MODEL PARAMETERS
# ===============================================================

print("\nIntercept")
print(model.intercept_)

print("\nCoefficients")

coefficients = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})

print(coefficients)

# Positive coefficient
# Increasing feature increases Profit

# Negative coefficient
# Increasing feature decreases Profit

# ===============================================================
# STEP 13 : MAKE PREDICTIONS
# ===============================================================

prediction = model.predict(X_test)

print("\nPrediction Completed")

# ===============================================================
# STEP 14 : ACTUAL VS PREDICTED
# ===============================================================

comparison = pd.DataFrame({
    "Actual Profit": y_test.values,
    "Predicted Profit": prediction
})

print("\nActual vs Predicted")
print(comparison.head(20))

# ===============================================================
# STEP 15 : MODEL EVALUATION
# ===============================================================

# Mean Absolute Error

mae = mean_absolute_error(y_test, prediction)

# Mean Squared Error

mse = mean_squared_error(y_test, prediction)

# Root Mean Squared Error

rmse = np.sqrt(mse)

# R2 Score

r2 = r2_score(y_test, prediction)

print("\nMODEL PERFORMANCE")
print("-"*40)

print("Mean Absolute Error :", mae)

print("Mean Squared Error :", mse)

print("Root Mean Squared Error :", rmse)

print("R2 Score :", r2)

# ===============================================================
# STEP 16 : PREDICT A NEW ORDER
# ===============================================================

mean_features = X.mean()

# Create a DataFrame for the new sample
new_wine_sample = pd.DataFrame([mean_features.values], columns=X.columns)

predicted_quality = model.predict(new_wine_sample)

print("\nPredicted Quality for New Wine Sample")
print(predicted_quality)

# ===============================================================
# STEP 17 : VISUALIZATION
# ===============================================================

plt.figure(figsize=(8,6))

plt.scatter(
    y_test,
    prediction
)

plt.xlabel("Actual Profit")

plt.ylabel("Predicted Profit")

plt.title("Actual Profit vs Predicted Profit")

plt.grid(True)

plt.show()

# ===============================================================
# STEP 18 : RESIDUAL ANALYSIS
# ===============================================================

# Residual = Actual - Predicted

residual = y_test - prediction

plt.figure(figsize=(8,6))

plt.scatter(
    prediction,
    residual
)

plt.axhline(
    y=0,
    color='red',
    linestyle='--'
)

plt.xlabel("Predicted Profit")

plt.ylabel("Residual")

plt.title("Residual Plot")

plt.grid(True)

plt.show()

# ===============================================================
# STEP 19 : FEATURE IMPORTANCE
# ===============================================================

plt.figure(figsize=(20,4))

plt.bar(
    coefficients["Feature"],
    coefficients["Coefficient"]
)

plt.title("Feature Importance")

plt.xlabel("Features")

plt.ylabel("Coefficient")

plt.show()