# -*- coding: utf-8 -*-
"""Workshop-1-python-and-ML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lT7qBPY4YyYsiOHiMY2Bv-LpMvGginuh
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, ConfusionMatrixDisplay, roc_curve, auc

print("="*80)
print("PGCB_compressed - CLASSIFICATION")
print("="*80)

# -----------------------------
# Step 1 : Import Libraries
# -----------------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)

# -------------------------------------------------------
# Step 2 : Load Dataset
# -------------------------------------------------------

df = pd.read_excel("PGCB_compressed.xlsx")

print("="*60)
print("FIRST FIVE RECORDS")
print("="*60)

print(df.head())

# -------------------------------------------------------
# Step 3 : Dataset Information
# -------------------------------------------------------

print("\n")
print("="*60)
print("DATASET INFORMATION")
print("="*60)

print(df.info())

# -------------------------------------------------------
# Step 4 : Statistical Summary
# -------------------------------------------------------

print("\n")
print("="*60)
print("STATISTICAL SUMMARY")
print("="*60)

print(df.describe())

# -------------------------------------------------------
# Step 5 : Check Missing Values
# -------------------------------------------------------

print("\n")
print("="*60)
print("MISSING VALUES")
print("="*60)

print(df.isnull().sum())

df["solar"] = df["solar"].fillna(df["solar"].mean())
df["wind"] = df["wind"].fillna(df["wind"].mean())
df["india_adani"] = df["india_adani"].fillna(df["india_adani"].mean())
df["nepal"] = df["nepal"].fillna(df["nepal"].mean())
df["remarks"] = df["remarks"].fillna(df["remarks"].mode()[0])

# -------------------------------------------------------
# Step 5 : Check Missing Values
# -------------------------------------------------------

print("\n")
print("="*60)
print("MISSING VALUES")
print("="*60)

print(df.isnull().sum())

# -------------------------------------------------------
# Step 10 : Separate Features and Target
# -------------------------------------------------------



X = df.drop(columns=["remarks", "datetime"])
y = df["remarks"]

# -------------------------------------------------------
# Step 11 : Train Test Split
# -------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining Samples :", len(X_train))
print("Testing Samples :", len(X_test))

# -------------------------------------------------------
# Step 12 : Train Logistic Regression Model
# -------------------------------------------------------

model = LogisticRegression(max_iter=500)

model.fit(X_train, y_train)

# -------------------------------------------------------
# Step 13 : Predict
# -------------------------------------------------------

y_pred = model.predict(X_test)

# -------------------------------------------------------
# Step 14 : Accuracy
# -------------------------------------------------------

accuracy = accuracy_score(y_test, y_pred)

print("\n")
print("="*60)
print("MODEL ACCURACY")
print("="*60)

print(f"Accuracy : {accuracy*100:.2f}%")

# -------------------------------------------------------
# Step 15 : Classification Report
# -------------------------------------------------------

print("\n")
print("="*60)
print("CLASSIFICATION REPORT")
print("="*60)

# Get unique classes from the target variable 'y'
target_labels = sorted(y.unique())

print(classification_report(
    y_test,
    y_pred,
    target_names=target_labels
))

# -------------------------------------------------------
# Step 16 : Confusion Matrix
# -------------------------------------------------------

cm = confusion_matrix(y_test, y_pred)

print("\n")
print("="*60)
print("CONFUSION MATRIX")
print("="*60)

print(cm)

# -------------------------------------------------------
# Step 17 : Plot Confusion Matrix
# -------------------------------------------------------

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=target_labels
)

disp.plot(cmap="Blues")

plt.title("Confusion Matrix")

plt.show()

# -------------------------------------------------------
# Step 18 : Feature Importance
# -------------------------------------------------------

importance = np.mean(np.abs(model.coef_), axis=0)

feature_names = X.columns

importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": importance
})

importance_df = importance_df.sort_values(
    by="Importance",
    ascending=False
)

print("\n")
print("="*60)
print("FEATURE IMPORTANCE")
print("="*60)

print(importance_df)

# -------------------------------------------------------
# Step 19 : Plot Feature Importance
# -------------------------------------------------------

plt.figure(figsize=(8,5))

plt.bar(
    importance_df["Feature"],
    importance_df["Importance"]
)

plt.title("Feature Importance")

plt.xlabel("Features")

plt.ylabel("Importance")

plt.xticks(rotation=20)

plt.show()

import matplotlib.pyplot as plt

# ------------------------------------------------------------------
# Models
# ------------------------------------------------------------------
models = {
    "Logistic Regression": LogisticRegression(max_iter=500),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "SVM": SVC(probability=True, random_state=42)
}

results = []

for name, model in models.items():
    print("\n"+"-"*60)
    print(name)
    print("-"*60)

    model.fit(X_train,y_train)
    pred = model.predict(X_test)

    acc = accuracy_score(y_test,pred)
    results.append([name,acc])

    print("Accuracy:",round(acc,4))
    print(classification_report(y_test,pred))

    cm = confusion_matrix(y_test,pred)
    disp = ConfusionMatrixDisplay(cm)
    disp.plot()
    plt.title(name)
    plt.show()

    if hasattr(model,"predict_proba"):
        prob = model.predict_proba(X_test)[:,1]
        fpr,tpr,_ = roc_curve(y_test,prob)
        roc_auc = auc(fpr,tpr)

        plt.figure(figsize=(5,5))
        plt.plot(fpr,tpr,label=f"AUC={roc_auc:.3f}")
        plt.plot([0,1],[0,1],"--")
        plt.xlabel("False Positive Rate")
        plt.ylabel("True Positive Rate")
        plt.title(name+" ROC Curve")
        plt.legend()
        plt.tight_layout()
        plt.show()

import pandas as pd

# -------------------------------------------------------
# Step 21 : Predict Multiple Remarks
# -------------------------------------------------------

# Create multiple sample inputs by duplicating the first row of X
# Ensure these samples have 13 features, matching the trained model
sample_input_1 = X.iloc[[0]]
sample_input_2 = X.iloc[[1]]
sample_input_3 = X.iloc[[2]]

# Concatenate them into a single DataFrame for prediction
new_samples = pd.concat([sample_input_1, sample_input_2, sample_input_3], ignore_index=True)

predictions = model.predict(new_samples)

print("\nMultiple Predictions")

for i in range(len(new_samples)):
    print(f"Sample {i+1} --> {predictions[i]}")

# -------------------------------------------------------
# Step 22 : Save Model
# -------------------------------------------------------

import joblib

joblib.dump(model, "iris_model.pkl")


print("\nModel Saved Successfully.")

# -------------------------------------------------------
# Step 23 : Load Saved Model and Predict
# -------------------------------------------------------

import pandas as pd

loaded_model = joblib.load("iris_model.pkl")

# Create a sample input with 13 features, similar to X
# We'll use the first row of X as an example
sample_input_for_loaded_model = X.iloc[[0]]

pred = loaded_model.predict(sample_input_for_loaded_model)

# The model directly predicts the remarks, so no inverse_transform is needed
species = pred[0]

print("\nPrediction Using Saved Model")

print(species)